{
  "SchemaVersion": 2,
  "CreatedAt": "2025-04-23T12:49:52.950544+03:00",
  "ArtifactName": ".",
  "ArtifactType": "filesystem",
  "Metadata": {
    "ImageConfig": {
      "architecture": "",
      "created": "0001-01-01T00:00:00Z",
      "os": "",
      "rootfs": {
        "type": "",
        "diff_ids": null
      },
      "config": {}
    }
  },
  "Results": [
    {
      "Target": "SCA/requirements.txt",
      "Class": "lang-pkgs",
      "Type": "pip",
      "Vulnerabilities": [
        {
          "VulnerabilityID": "CVE-2022-29217",
          "PkgName": "PyJWT",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/pyjwt@1.7.1",
            "UID": "9e1e984490983dd9"
          },
          "InstalledVersion": "1.7.1",
          "FixedVersion": "2.4.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2022-29217",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-jwt: Key confusion through non-blocklisted public key formats",
          "Description": "PyJWT is a Python implementation of RFC 7519. PyJWT supports multiple different JWT signing algorithms. With JWT, an attacker submitting the JWT token can choose the used signing algorithm. The PyJWT library requires that the application chooses what algorithms are supported. The application can specify `jwt.algorithms.get_default_algorithms()` to get support for all algorithms, or specify a single algorithm. The issue is not that big as `algorithms=jwt.algorithms.get_default_algorithms()` has to be used. Users should upgrade to v2.4.0 to receive a patch for this issue. As a workaround, always be explicit with the algorithms that are accepted and expected when decoding.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-327"
          ],
          "VendorSeverity": {
            "amazon": 2,
            "cbl-mariner": 3,
            "ghsa": 3,
            "nvd": 3,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N",
              "V3Score": 7.4
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:P/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:H/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2022-29217",
            "https://github.com/jpadilla/pyjwt",
            "https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc",
            "https://github.com/jpadilla/pyjwt/commit/9c528670c455b8d948aff95ed50e22940d1ad3fc (2.4.0)",
            "https://github.com/jpadilla/pyjwt/releases/tag/2.4.0",
            "https://github.com/jpadilla/pyjwt/security/advisories/GHSA-ffqj-6fqr-9h24",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pyjwt/PYSEC-2022-202.yaml",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX/",
            "https://lists.fedoraproject.org/archives/list/package-announce%40lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/5PK7IQCBVNLYJEFTPHBBPFP72H4WUFNX",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/6HIYEYZRQEP6QTHT3EHH3RGFYJIHIMAO",
            "https://nvd.nist.gov/vuln/detail/CVE-2022-29217",
            "https://ubuntu.com/security/notices/USN-5526-1",
            "https://ubuntu.com/security/notices/USN-5526-2",
            "https://www.cve.org/CVERecord?id=CVE-2022-29217",
            "https://www.vicarius.io/vsociety/posts/risky-algorithms-algorithm-confusion-in-pyjwt-cve-2022-29217"
          ],
          "PublishedDate": "2022-05-24T15:15:07.767Z",
          "LastModifiedDate": "2024-11-21T06:58:44.463Z"
        },
        {
          "VulnerabilityID": "CVE-2020-14343",
          "PkgName": "PyYAML",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/pyyaml@4.2b1",
            "UID": "2c1270d99a1cc69"
          },
          "InstalledVersion": "4.2b1",
          "FixedVersion": "5.4",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2020-14343",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "PyYAML: incomplete fix for CVE-2020-1747",
          "Description": "A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.",
          "Severity": "CRITICAL",
          "CweIDs": [
            "CWE-20"
          ],
          "VendorSeverity": {
            "alma": 2,
            "cbl-mariner": 4,
            "ghsa": 4,
            "nvd": 4,
            "oracle-oval": 2,
            "photon": 4,
            "redhat": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:C/I:C/A:C",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V2Score": 10,
              "V3Score": 9.8
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
              "V3Score": 9.8
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2020-14343",
            "https://bugzilla.redhat.com/show_bug.cgi?id=1860466",
            "https://errata.almalinux.org/8/ALSA-2021-2583.html",
            "https://github.com/SeldonIO/seldon-core/issues/2252",
            "https://github.com/advisories/GHSA-8q59-q68h-6hv4",
            "https://github.com/pypa/advisory-database/tree/main/vulns/pyyaml/PYSEC-2021-142.yaml",
            "https://github.com/yaml/pyyaml",
            "https://github.com/yaml/pyyaml/commit/a001f2782501ad2d24986959f0239a354675f9dc",
            "https://github.com/yaml/pyyaml/issues/420",
            "https://github.com/yaml/pyyaml/issues/420#issuecomment-663673966",
            "https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation",
            "https://linux.oracle.com/cve/CVE-2020-14343.html",
            "https://linux.oracle.com/errata/ELSA-2021-2583.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2020-14343",
            "https://pypi.org/project/PyYAML",
            "https://ubuntu.com/security/notices/USN-4940-1",
            "https://www.cve.org/CVERecord?id=CVE-2020-14343",
            "https://www.oracle.com/security-alerts/cpuapr2022.html",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2021-02-09T21:15:12.707Z",
          "LastModifiedDate": "2024-11-21T05:03:03.217Z"
        },
        {
          "VulnerabilityID": "CVE-2018-1000656",
          "PkgName": "flask",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/flask@0.12",
            "UID": "ca2d9b3c2b4e641a"
          },
          "InstalledVersion": "0.12",
          "FixedVersion": "0.12.3",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2018-1000656",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-flask: Denial of Service via crafted JSON file",
          "Description": "The Pallets Project flask version Before 0.12.3 contains a CWE-20: Improper Input Validation vulnerability in flask that can result in Large amount of memory usage possibly leading to denial of service. This attack appear to be exploitable via Attacker provides JSON data in incorrect encoding. This vulnerability appears to have been fixed in 0.12.3. NOTE: this may overlap CVE-2019-1010083.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-20"
          ],
          "VendorSeverity": {
            "ghsa": 3,
            "nvd": 3,
            "redhat": 1,
            "ubuntu": 1
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2018-1000656",
            "https://github.com/advisories/GHSA-562c-5r94-xh97",
            "https://github.com/pallets/flask",
            "https://github.com/pallets/flask/commit/b178e89e4456e777b1a7ac6d7199052d0dfdbbbe",
            "https://github.com/pallets/flask/pull/2691",
            "https://github.com/pallets/flask/releases/tag/0.12.3",
            "https://github.com/pypa/advisory-database/tree/main/vulns/flask/PYSEC-2018-66.yaml",
            "https://lists.debian.org/debian-lts-announce/2019/08/msg00025.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2018-1000656",
            "https://security.netapp.com/advisory/ntap-20190221-0001",
            "https://security.netapp.com/advisory/ntap-20190221-0001/",
            "https://ubuntu.com/security/notices/USN-4378-1",
            "https://usn.ubuntu.com/4378-1",
            "https://usn.ubuntu.com/4378-1/",
            "https://www.cve.org/CVERecord?id=CVE-2018-1000656"
          ],
          "PublishedDate": "2018-08-20T19:31:45.34Z",
          "LastModifiedDate": "2024-11-21T03:40:20.45Z"
        },
        {
          "VulnerabilityID": "CVE-2019-1010083",
          "PkgName": "flask",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/flask@0.12",
            "UID": "ca2d9b3c2b4e641a"
          },
          "InstalledVersion": "0.12",
          "FixedVersion": "1.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2019-1010083",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-flask: unexpected memory usage can lead to denial of service via crafted encoded JSON data",
          "Description": "The Pallets Project Flask before 1.0 is affected by: unexpected memory usage. The impact is: denial of service. The attack vector is: crafted encoded JSON data. The fixed version is: 1. NOTE: this may overlap CVE-2018-1000656.",
          "Severity": "HIGH",
          "VendorSeverity": {
            "ghsa": 3,
            "nvd": 3,
            "redhat": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:N/I:N/A:P",
              "V3Vector": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2019-1010083",
            "https://github.com/advisories/GHSA-5wv5-4vpf-pj6m",
            "https://github.com/pallets/flask",
            "https://github.com/pypa/advisory-database/tree/main/vulns/flask/PYSEC-2019-179.yaml",
            "https://nvd.nist.gov/vuln/detail/CVE-2019-1010083",
            "https://palletsprojects.com/blog/flask-1-0-released/",
            "https://snyk.io/vuln/SNYK-PYTHON-FLASK-451637",
            "https://www.cve.org/CVERecord?id=CVE-2019-1010083",
            "https://www.palletsprojects.com/blog/flask-1-0-released",
            "https://www.palletsprojects.com/blog/flask-1-0-released/"
          ],
          "PublishedDate": "2019-07-17T14:15:11.57Z",
          "LastModifiedDate": "2024-11-21T04:17:57.66Z"
        },
        {
          "VulnerabilityID": "CVE-2023-30861",
          "PkgName": "flask",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/flask@0.12",
            "UID": "ca2d9b3c2b4e641a"
          },
          "InstalledVersion": "0.12",
          "FixedVersion": "2.3.2, 2.2.5",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-30861",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "flask: Possible disclosure of permanent session cookie due to missing Vary: Cookie header",
          "Description": "Flask is a lightweight WSGI web application framework. When all of the following conditions are met, a response containing data intended for one client may be cached and subsequently sent by the proxy to other clients. If the proxy also caches `Set-Cookie` headers, it may send one client's `session` cookie to other clients. The severity depends on the application's use of the session and the proxy's behavior regarding cookies. The risk depends on all these conditions being met.\n\n1. The application must be hosted behind a caching proxy that does not strip cookies or ignore responses with cookies.\n2. The application sets `session.permanent = True`\n3. The application does not access or modify the session at any point during a request.\n4. `SESSION_REFRESH_EACH_REQUEST` enabled (the default).\n5. The application does not set a `Cache-Control` header to indicate that a page is private or should not be cached.\n\nThis happens because vulnerable versions of Flask only set the `Vary: Cookie` header when the session is accessed or modified, not when it is refreshed (re-sent to update the expiration) without being accessed or modified. This issue has been fixed in versions 2.3.2 and 2.2.5.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-539"
          ],
          "VendorSeverity": {
            "amazon": 3,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 3,
            "redhat": 3,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            }
          },
          "References": [
            "https://access.redhat.com/security/cve/CVE-2023-30861",
            "https://github.com/pallets/flask",
            "https://github.com/pallets/flask/commit/70f906c51ce49c485f1d355703e9cc3386b1cc2b",
            "https://github.com/pallets/flask/commit/8646edca6f47e2cd57464081b3911218d4734f8d (2.2.5)",
            "https://github.com/pallets/flask/commit/8705dd39c4fa563ea0fe0bf84c85da8fcc98b88d (2.3.2)",
            "https://github.com/pallets/flask/commit/afd63b16170b7c047f5758eb910c416511e9c965",
            "https://github.com/pallets/flask/releases/tag/2.2.5",
            "https://github.com/pallets/flask/releases/tag/2.3.2",
            "https://github.com/pallets/flask/security/advisories/GHSA-m2qf-hxjv-5gpq",
            "https://github.com/pypa/advisory-database/tree/main/vulns/flask/PYSEC-2023-62.yaml",
            "https://linux.oracle.com/cve/CVE-2023-30861.html",
            "https://linux.oracle.com/errata/ELSA-2023-12710.html",
            "https://lists.debian.org/debian-lts-announce/2023/08/msg00024.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-30861",
            "https://security.netapp.com/advisory/ntap-20230818-0006",
            "https://security.netapp.com/advisory/ntap-20230818-0006/",
            "https://ubuntu.com/security/notices/USN-6111-1",
            "https://www.cve.org/CVERecord?id=CVE-2023-30861",
            "https://www.debian.org/security/2023/dsa-5442"
          ],
          "PublishedDate": "2023-05-02T18:15:52.373Z",
          "LastModifiedDate": "2024-11-21T08:00:59.623Z"
        },
        {
          "VulnerabilityID": "CVE-2018-18074",
          "PkgName": "requests",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/requests@2.19.0",
            "UID": "80823eba7aafe502"
          },
          "InstalledVersion": "2.19.0",
          "FixedVersion": "2.20.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2018-18074",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-requests: Redirect from HTTPS to HTTP does not remove Authorization header",
          "Description": "The Requests package before 2.20.0 for Python sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network.",
          "Severity": "HIGH",
          "CweIDs": [
            "CWE-522"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "ghsa": 3,
            "nvd": 3,
            "oracle-oval": 2,
            "photon": 3,
            "redhat": 1,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V3Score": 7.5
            },
            "nvd": {
              "V2Vector": "AV:N/AC:L/Au:N/C:P/I:N/A:N",
              "V3Vector": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
              "V2Score": 5,
              "V3Score": 7.5
            },
            "redhat": {
              "V3Vector": "CVSS:3.0/AV:A/AC:H/PR:N/UI:R/S:U/C:L/I:N/A:N",
              "V3Score": 2.6
            }
          },
          "References": [
            "http://docs.python-requests.org/en/master/community/updates/#release-and-version-history",
            "http://lists.opensuse.org/opensuse-security-announce/2019-07/msg00024.html",
            "https://access.redhat.com/errata/RHSA-2019:2035",
            "https://access.redhat.com/security/cve/CVE-2018-18074",
            "https://bugs.debian.org/910766",
            "https://errata.almalinux.org/8/ALSA-2020-1605.html",
            "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2018-28.yaml",
            "https://github.com/requests/requests",
            "https://github.com/requests/requests/commit/c45d7c49ea75133e52ab22a8e9e13173938e36ff",
            "https://github.com/requests/requests/issues/4716",
            "https://github.com/requests/requests/pull/4718",
            "https://linux.oracle.com/cve/CVE-2018-18074.html",
            "https://linux.oracle.com/errata/ELSA-2020-2081.html",
            "https://nvd.nist.gov/vuln/detail/CVE-2018-18074",
            "https://ubuntu.com/security/notices/USN-3790-1",
            "https://ubuntu.com/security/notices/USN-3790-2",
            "https://usn.ubuntu.com/3790-1",
            "https://usn.ubuntu.com/3790-1/",
            "https://usn.ubuntu.com/3790-2",
            "https://usn.ubuntu.com/3790-2/",
            "https://www.cve.org/CVERecord?id=CVE-2018-18074",
            "https://www.oracle.com/security-alerts/cpujul2022.html"
          ],
          "PublishedDate": "2018-10-09T17:29:01.897Z",
          "LastModifiedDate": "2024-11-21T03:55:26.53Z"
        },
        {
          "VulnerabilityID": "CVE-2023-32681",
          "PkgName": "requests",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/requests@2.19.0",
            "UID": "80823eba7aafe502"
          },
          "InstalledVersion": "2.19.0",
          "FixedVersion": "2.31.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2023-32681",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "python-requests: Unintended leak of Proxy-Authorization header",
          "Description": "Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use `rebuild_proxies` to reattach the `Proxy-Authorization` header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the `Proxy-Authorization` header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-200"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "cbl-mariner": 2,
            "ghsa": 2,
            "nvd": 2,
            "oracle-oval": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
              "V3Score": 6.1
            },
            "nvd": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
              "V3Score": 6.1
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:N/AC:H/PR:N/UI:R/S:C/C:H/I:N/A:N",
              "V3Score": 6.1
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2023:4350",
            "https://access.redhat.com/security/cve/CVE-2023-32681",
            "https://bugzilla.redhat.com/2209469",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2209469",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2023-32681",
            "https://errata.almalinux.org/9/ALSA-2023-4350.html",
            "https://errata.rockylinux.org/RLSA-2023:4520",
            "https://github.com/psf/requests",
            "https://github.com/psf/requests/commit/74ea7cf7a6a27a4eeb2ae24e162bcc942a6706d5",
            "https://github.com/psf/requests/releases/tag/v2.31.0",
            "https://github.com/psf/requests/security/advisories/GHSA-j8r2-6x86-q33q",
            "https://github.com/pypa/advisory-database/tree/main/vulns/requests/PYSEC-2023-74.yaml",
            "https://linux.oracle.com/cve/CVE-2023-32681.html",
            "https://linux.oracle.com/errata/ELSA-2023-7050.html",
            "https://lists.debian.org/debian-lts-announce/2023/06/msg00018.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/AW7HNFGYP44RT3DUDQXG2QT3OEV2PJ7Y/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/KOYASTZDGQG2BWLSNBPL3TQRL2G7QYNZ/",
            "https://nvd.nist.gov/vuln/detail/CVE-2023-32681",
            "https://security.gentoo.org/glsa/202309-08",
            "https://ubuntu.com/security/notices/USN-6155-1",
            "https://ubuntu.com/security/notices/USN-6155-2",
            "https://www.cve.org/CVERecord?id=CVE-2023-32681"
          ],
          "PublishedDate": "2023-05-26T18:15:14.147Z",
          "LastModifiedDate": "2025-02-13T17:16:32.583Z"
        },
        {
          "VulnerabilityID": "CVE-2024-35195",
          "PkgName": "requests",
          "PkgIdentifier": {
            "PURL": "pkg:pypi/requests@2.19.0",
            "UID": "80823eba7aafe502"
          },
          "InstalledVersion": "2.19.0",
          "FixedVersion": "2.32.0",
          "Status": "fixed",
          "Layer": {},
          "SeveritySource": "ghsa",
          "PrimaryURL": "https://avd.aquasec.com/nvd/cve-2024-35195",
          "DataSource": {
            "ID": "ghsa",
            "Name": "GitHub Security Advisory pip",
            "URL": "https://github.com/advisories?query=type%3Areviewed+ecosystem%3Apip"
          },
          "Title": "requests: subsequent requests to the same host ignore cert verification",
          "Description": "Requests is a HTTP library. Prior to 2.32.0, when making requests through a Requests `Session`, if the first request is made with `verify=False` to disable cert verification, all subsequent requests to the same host will continue to ignore cert verification regardless of changes to the value of `verify`. This behavior will continue for the lifecycle of the connection in the connection pool. This vulnerability is fixed in 2.32.0.",
          "Severity": "MEDIUM",
          "CweIDs": [
            "CWE-670"
          ],
          "VendorSeverity": {
            "alma": 2,
            "amazon": 2,
            "azure": 2,
            "cbl-mariner": 2,
            "ghsa": 2,
            "oracle-oval": 2,
            "photon": 2,
            "redhat": 2,
            "rocky": 2,
            "ubuntu": 2
          },
          "CVSS": {
            "ghsa": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
              "V3Score": 5.6
            },
            "redhat": {
              "V3Vector": "CVSS:3.1/AV:L/AC:H/PR:H/UI:R/S:U/C:H/I:H/A:N",
              "V3Score": 5.6
            }
          },
          "References": [
            "https://access.redhat.com/errata/RHSA-2025:0012",
            "https://access.redhat.com/security/cve/CVE-2024-35195",
            "https://bugzilla.redhat.com/2282114",
            "https://bugzilla.redhat.com/show_bug.cgi?id=2282114",
            "https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2024-35195",
            "https://errata.almalinux.org/8/ALSA-2025-0012.html",
            "https://errata.rockylinux.org/RLSA-2025:0012",
            "https://github.com/psf/requests",
            "https://github.com/psf/requests/commit/a58d7f2ffb4d00b46dca2d70a3932a0b37e22fac",
            "https://github.com/psf/requests/pull/6655",
            "https://github.com/psf/requests/security/advisories/GHSA-9wx4-h78v-vm56",
            "https://linux.oracle.com/cve/CVE-2024-35195.html",
            "https://linux.oracle.com/errata/ELSA-2025-0012.html",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IYLSNK5TL46Q6XPRVMHVWS63MVJQOK4Q/",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ",
            "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/N7WP6EYDSUOCOJYHDK5NX43PYZ4SNHGZ/",
            "https://nvd.nist.gov/vuln/detail/CVE-2024-35195",
            "https://www.cve.org/CVERecord?id=CVE-2024-35195"
          ],
          "PublishedDate": "2024-05-20T21:15:09.99Z",
          "LastModifiedDate": "2024-11-21T09:19:54.51Z"
        }
      ]
    }
  ]
}
